- id: '1748766727705'
  alias: Cody's Bedtime
  description: Beditme routine for when phone is plugged in.
  triggers:
  - type: plugged_in
    device_id: 9381be378546e86a3bd680eacd722591
    entity_id: 593c3a4a231b06acfeb66c15112398aa
    domain: binary_sensor
    trigger: device
  conditions:
  - condition: time
    after: '20:00:00'
    before: 04:00:00
    weekday:
    - sat
    - fri
    - thu
    - wed
    - tue
    - mon
    - sun
  - condition: state
    entity_id: input_boolean.stop_bedtime_routine_cody
    state: 'off'
  actions:
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      area_id: bedroom
  mode: single
- id: '1748621098096'
  alias: Battery Low Counter
  description: ''
  triggers:
  - type: bat_low
    device_id: ad535e51b7dce956da05000a026e15c4
    entity_id: 9dcedfb9314640afb811425cc587299e
    domain: binary_sensor
    trigger: device
  - type: bat_low
    device_id: 61e80e02efd9da3303b6ef7c8f6e4e8c
    entity_id: eef283279cc7481167d4bb9435de57ea
    domain: binary_sensor
    trigger: device
  - type: bat_low
    device_id: db41608863db7d4a87b65fc9b2dd1076
    entity_id: 222534d1c3773e9604eadecbd4324525
    domain: binary_sensor
    trigger: device
  - type: bat_low
    device_id: 5fecffbe3f3a4606689a9836f8e050fc
    entity_id: e1ff5e255c27a4926f52362e261d495d
    domain: binary_sensor
    trigger: device
  - type: bat_low
    device_id: d5c08270d95cf0d00fa820ff94a0b86c
    entity_id: 273179ecebe8b54e086f84d63d4df666
    domain: binary_sensor
    trigger: device
  - type: bat_low
    device_id: e64b0f0f3b67d1f854908934448b9c72
    entity_id: d1485787ea27030b12805a2026d7e657
    domain: binary_sensor
    trigger: device
  conditions: []
  actions:
  - action: counter.increment
    metadata: {}
    data: {}
    target:
      entity_id: counter.batter_low_counter
  mode: single
- id: '1748621214332'
  alias: Batter Low Counter - Reset
  description: ''
  triggers:
  - type: not_bat_low
    device_id: ad535e51b7dce956da05000a026e15c4
    entity_id: 9dcedfb9314640afb811425cc587299e
    domain: binary_sensor
    trigger: device
  - type: not_bat_low
    device_id: 61e80e02efd9da3303b6ef7c8f6e4e8c
    entity_id: eef283279cc7481167d4bb9435de57ea
    domain: binary_sensor
    trigger: device
  - type: not_bat_low
    device_id: db41608863db7d4a87b65fc9b2dd1076
    entity_id: 222534d1c3773e9604eadecbd4324525
    domain: binary_sensor
    trigger: device
  - type: not_bat_low
    device_id: 5fecffbe3f3a4606689a9836f8e050fc
    entity_id: e1ff5e255c27a4926f52362e261d495d
    domain: binary_sensor
    trigger: device
  - type: not_bat_low
    device_id: d5c08270d95cf0d00fa820ff94a0b86c
    entity_id: 273179ecebe8b54e086f84d63d4df666
    domain: binary_sensor
    trigger: device
  - type: not_bat_low
    device_id: e64b0f0f3b67d1f854908934448b9c72
    entity_id: d1485787ea27030b12805a2026d7e657
    domain: binary_sensor
    trigger: device
  conditions: []
  actions:
  - action: counter.decrement
    metadata: {}
    data: {}
    target:
      entity_id: counter.batter_low_counter
  mode: single
- id: bedroom_fan_morning
  alias: Auto Off - MBR Fan - 6:15 AM
  description: Turns off the Master bedroom fan at 6:15 AM
  triggers:
  - trigger: time
    at: 06:15:00
  conditions:
  - condition: device
    type: is_on
    device_id: 9b5f103c6f070811a4a779daec9a3417
    entity_id: e8fa8bada3c4e7e75dfc161228f0514a
    domain: switch
  actions:
  - type: turn_off
    device_id: 9b5f103c6f070811a4a779daec9a3417
    entity_id: e8fa8bada3c4e7e75dfc161228f0514a
    domain: switch
  mode: single
- id: '1748567259194'
  alias: Dryer running
  description: ''
  triggers:
  - type: vibration
    device_id: 61e80e02efd9da3303b6ef7c8f6e4e8c
    entity_id: 82b5466a7ce138f6824efda852d876b5
    domain: binary_sensor
    trigger: device
  conditions:
  - condition: state
    entity_id: input_boolean.dryer_running
    state: 'off'
  actions:
  - action: counter.increment
    metadata: {}
    data: {}
    target:
      entity_id: counter.dryer_vibration_counter
  - condition: numeric_state
    entity_id: counter.dryer_vibration_counter
    above: 20
  - action: input_boolean.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.dryer_running
  mode: single
- id: '1748567409416'
  alias: Washer Running & Finish notification
  description: ''
  triggers:
  - type: current
    device_id: 73cfac6ba418fbfdfd041791f1b79183
    entity_id: 855a49eb4a5e4a51339de34dd6e642e5
    domain: sensor
    trigger: device
    above: 0.04
  conditions: []
  actions:
  - action: input_boolean.turn_on
    metadata: {}
    data: {}
    target:
      entity_id:
      - input_boolean.washer_running
  - wait_for_trigger:
    - type: frequency
      device_id: 73cfac6ba418fbfdfd041791f1b79183
      entity_id: 9e0b0c06126d1843da3dd7f28a2650f7
      domain: sensor
      trigger: device
      below: 0.05
  - action: input_boolean.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.washer_running
  - action: notify.alexa_media_kitchen_dot
    data:
      message: The Washer is finished.
  - action: notify.alexa_media_cody_s_desk_echo_dot
    data:
      message: The Washer is finished.
  mode: single
- id: '1748567585742'
  alias: Dryer Finished
  description: ''
  triggers:
  - type: no_vibration
    device_id: 61e80e02efd9da3303b6ef7c8f6e4e8c
    entity_id: 82b5466a7ce138f6824efda852d876b5
    domain: binary_sensor
    trigger: device
    for:
      hours: 0
      minutes: 2
      seconds: 0
  conditions:
  - condition: state
    entity_id: input_boolean.dryer_running
    state: 'on'
  actions:
  - action: counter.reset
    metadata: {}
    data: {}
    target:
      entity_id: counter.dryer_vibration_counter
  - action: input_boolean.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.dryer_running
  - action: notify.alexa_media_kitchen_dot
    data:
      message: The Dryer is finished.
  - action: notify.alexa_media_cody_s_desk_echo_dot
    data:
      message: The Dryer is finished.
  mode: single
- id: '1748766866371'
  alias: Cody Awake
  description: Morning routine for when Cody's phone is unplugged in the morning.
  triggers:
  - type: not_plugged_in
    device_id: 9381be378546e86a3bd680eacd722591
    entity_id: 593c3a4a231b06acfeb66c15112398aa
    domain: binary_sensor
    trigger: device
  conditions:
  - condition: time
    after: 05:30:00
    before: 08:00:00
    weekday:
    - sat
    - fri
    - thu
    - wed
    - tue
    - mon
    - sun
  actions:
  - action: light.turn_on
    metadata: {}
    data:
      brightness_pct: 50
    target:
      area_id: bedroom
  mode: single
- id: '1748836412915'
  alias: Kris Awake
  description: Morning routine for when Kris's phone is unplugged in the morning.
  triggers:
  - type: not_plugged_in
    device_id: 922ce8aeab0a2d9c6e2154210dd91ef1
    entity_id: b00af0f4c796fcbf2085643ffedd299f
    domain: binary_sensor
    trigger: device
  conditions:
  - condition: time
    after: 05:30:00
    before: 08:00:00
    weekday:
    - sat
    - fri
    - thu
    - wed
    - tue
    - mon
    - sun
  actions:
  - action: light.turn_on
    metadata: {}
    data:
      brightness_pct: 10
    target:
      device_id: eee172d01883d5535bec5579d55a8ad7
  - delay:
      hours: 0
      minutes: 20
      seconds: 0
      milliseconds: 0
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      area_id: bedroom
  mode: single
- id: '1748916145233'
  alias: Auto Lights - Pantry - Motion
  description: ''
  triggers:
  - type: occupied
    device_id: e64b0f0f3b67d1f854908934448b9c72
    entity_id: 52464e9c0edd4c10bc37a4a89abeffa3
    domain: binary_sensor
    trigger: device
  conditions: []
  actions:
  - action: light.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: light.pantry_light
  - wait_for_trigger:
    - type: not_occupied
      device_id: e64b0f0f3b67d1f854908934448b9c72
      entity_id: 52464e9c0edd4c10bc37a4a89abeffa3
      domain: binary_sensor
      trigger: device
  - type: turn_off
    device_id: 8c79fd93c7e6cb55beb5758f59ff1b01
    entity_id: 0a88867727d9b4709f69dc11f0b9766f
    domain: light
  mode: single
- id: '1748923055706'
  alias: NFC - Cody Bedtime Stop
  description: ''
  triggers:
  - trigger: tag
    tag_id: '2'
  conditions: []
  actions:
  - action: input_boolean.toggle
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.stop_bedtime_routine_cody
  - wait_for_trigger:
    - trigger: time
      at: 01:00:00
  - action: input_boolean.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.stop_bedtime_routine_cody
  mode: single
- id: '1748923765614'
  alias: Kris Bedtime
  description: Beditme routine for when phone is plugged in.
  triggers:
  - type: plugged_in
    device_id: 922ce8aeab0a2d9c6e2154210dd91ef1
    entity_id: b00af0f4c796fcbf2085643ffedd299f
    domain: binary_sensor
    trigger: device
  conditions:
  - condition: time
    after: '20:00:00'
    before: 04:00:00
    weekday:
    - sat
    - fri
    - thu
    - wed
    - tue
    - mon
    - sun
  actions:
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      area_id: bedroom
  mode: single
- id: '1749007397033'
  alias: Tag Kris To-Do is scanned
  description: ''
  triggers:
  - trigger: tag
    tag_id: Kris To Do
  conditions: []
  actions:
  - action: notify.alexa_media_kitchen_dot
    data:
      message: You have {{ states('todo.kris_s_to_do') }} items on your To-Do list.
  mode: single
- id: '1749008555609'
  alias: Tag Cody To-Do is scanned
  description: ''
  triggers:
  - trigger: tag
    tag_id: Cody To Do
  conditions: []
  actions:
  - action: notify.alexa_media_kitchen_dot
    data:
      message: You have {{ states('todo.cody_s_to_do') }} items on your To-Do list.
  mode: single
- id: '1749365676704'
  alias: Auto Off - All Lights - 1:00 AM
  description: ''
  triggers:
  - trigger: time
    at: 01:00:00
  conditions: []
  actions:
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      floor_id: second_floor
  mode: single
- id: '1749430100271'
  alias: Auto Lights - Reptiles - Time
  description: ''
  triggers:
  - trigger: time
    at: 06:15:00
  conditions: []
  actions:
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.reptile_uvb
  - wait_for_trigger:
    - trigger: time
      at: '21:30:00'
  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.reptile_uvb
  mode: single
- id: '1749703338431'
  alias: Tag Pantry is scanned
  description: ''
  triggers:
  - trigger: tag
    tag_id: Pantry
  conditions: []
  actions:
  - action: light.toggle
    metadata: {}
    data: {}
    target:
      area_id: pantry
  mode: single
- id: '1749703362616'
  alias: Tag Kitchen is scanned
  description: ''
  triggers:
  - trigger: tag
    tag_id: Kitchen
  conditions: []
  actions:
  - action: light.toggle
    metadata: {}
    data: {}
    target:
      area_id: kitchen
  mode: single
- id: '1749703394412'
  alias: Tag Guest Bedroom is scanned
  description: ''
  triggers:
  - trigger: tag
    tag_id: Guest Bedroom
  conditions: []
  actions:
  - action: light.toggle
    metadata: {}
    data: {}
    target:
      entity_id: light.guest_bedroom
  mode: single
- id: '1749703418876'
  alias: Tag Master Bedroom is scanned
  description: ''
  triggers:
  - trigger: tag
    tag_id: 'Master Bedroom '
  conditions: []
  actions:
  - action: light.toggle
    metadata: {}
    data: {}
    target:
      area_id: bedroom
  mode: single
- id: '1749703447371'
  alias: Tag Master Closet is scanned
  description: ''
  triggers:
  - trigger: tag
    tag_id: Master Closet
  conditions: []
  actions:
  - action: light.toggle
    metadata: {}
    data: {}
    target:
      entity_id: light.master_closet
  mode: single
- id: '1749774495213'
  alias: Auto Lights - Laundry Room - Motion
  description: ''
  triggers:
  - type: occupied
    device_id: 8633d6d2f58b3eeab10f65cb8b285d29
    entity_id: b60e575a809b353549b17a4c0f20800b
    domain: binary_sensor
    trigger: device
  conditions: []
  actions:
  - type: turn_on
    device_id: aa7e375127eb9d42aa7120e84302971f
    entity_id: 6427d26ad5d9a95c5692bf83f86a859f
    domain: light
  - wait_for_trigger:
    - type: not_occupied
      device_id: 8633d6d2f58b3eeab10f65cb8b285d29
      entity_id: b60e575a809b353549b17a4c0f20800b
      domain: binary_sensor
      trigger: device
  - type: turn_off
    device_id: aa7e375127eb9d42aa7120e84302971f
    entity_id: 6427d26ad5d9a95c5692bf83f86a859f
    domain: light
  mode: single
- id: '1749775911959'
  alias: Auto Lights - Master Closet - Motion
  description: ''
  triggers:
  - type: occupied
    device_id: 1ca092abc445a29294c3a258b0c0b49c
    entity_id: f7aa2bdff91cbeb40166a18add9ae326
    domain: binary_sensor
    trigger: device
  conditions:
  - condition: or
    conditions:
    - condition: state
      entity_id: light.master_bedroom
      state: 'on'
    - condition: state
      entity_id: schedule.closet_schedule
      state: ''
  actions:
  - action: light.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: light.master_closet
  - wait_for_trigger:
    - type: not_occupied
      device_id: 1ca092abc445a29294c3a258b0c0b49c
      entity_id: f7aa2bdff91cbeb40166a18add9ae326
      domain: binary_sensor
      trigger: device
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: light.master_closet
  mode: single
- id: '1749777982957'
  alias: Auto Lights - Kitchen - Vibration
  description: ''
  triggers:
  - type: vibration
    device_id: ad535e51b7dce956da05000a026e15c4
    entity_id: f5d132311de9119488b7399cfbbe5b9b
    domain: binary_sensor
    trigger: device
  conditions: []
  actions:
  - action: light.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: light.kitchen
  - wait_for_trigger:
    - type: no_vibration
      device_id: ad535e51b7dce956da05000a026e15c4
      entity_id: f5d132311de9119488b7399cfbbe5b9b
      domain: binary_sensor
      trigger: device
      for:
        hours: 0
        minutes: 10
        seconds: 0
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: light.kitchen
  mode: single
- id: '1749784009249'
  alias: Dishwasher Running
  description: ''
  triggers:
  - type: vibration
    device_id: 8e1d404d69fe8466e7b003d282371b50
    entity_id: 43155d5581ea4599de8fb99cfb09e46e
    domain: binary_sensor
    trigger: device
  conditions:
  - condition: state
    entity_id: input_boolean.dishwasher_running
    state: 'off'
  actions:
  - action: counter.increment
    metadata: {}
    data: {}
    target:
      entity_id: counter.dishwasher_vibration_counter
  - condition: numeric_state
    entity_id: counter.dishwasher_vibration_counter
    above: 20
  - action: input_boolean.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.dishwasher_running
  mode: single
- id: '1749784253177'
  alias: Dishwasher Finished
  description: ''
  triggers:
  - type: no_vibration
    device_id: 8e1d404d69fe8466e7b003d282371b50
    entity_id: 43155d5581ea4599de8fb99cfb09e46e
    domain: binary_sensor
    trigger: device
    for:
      hours: 0
      minutes: 2
      seconds: 0
  conditions:
  - condition: state
    entity_id: input_boolean.dishwasher_running
    state: 'on'
  actions:
  - action: counter.reset
    metadata: {}
    data: {}
    target:
      entity_id: counter.dishwasher_vibration_counter
  - action: input_boolean.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.dishwasher_running
  - action: notify.alexa_media_kitchen_dot
    data:
      message: The Dishwasher is finished.
  - action: notify.alexa_media_cody_s_desk_echo_dot
    data:
      message: The Dishwasher is finished.
  mode: single
- id: '1749785160667'
  alias: Cactus humidity below 20
  description: ''
  triggers:
  - type: humidity
    device_id: 9e49546c7dec3189d608993bb3de8eea
    entity_id: 1271b93e4fa4628395eab3bac79bb805
    domain: sensor
    trigger: device
    below: 20
    for:
      hours: 0
      minutes: 30
      seconds: 0
  conditions: []
  actions:
  - action: input_boolean.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.cactus_needs_water
  - wait_for_trigger:
    - type: humidity
      device_id: 9e49546c7dec3189d608993bb3de8eea
      entity_id: 1271b93e4fa4628395eab3bac79bb805
      domain: sensor
      trigger: device
      above: 20
  - action: input_boolean.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.cactus_needs_water
  mode: single
