#################################################################
## Home Assistant Core
#################################################################
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Change Logs from SQLite to MariaDB
recorder:
  db_url: !secret mariadb_url

#################################################################
## Components
#################################################################

battery_notes:

#################################################################
## Notifications
#################################################################

#################################################################
## Includes
#################################################################

automation manual: !include_dir_merge_list automation/
automation UI: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
